openapi: 3.0.0
info:
  title: ComplianceIQ Backend API
  version: 1.0.0
paths:
  /read_pdf:
    get:
      summary: Fetch PDF content from Google Drive
      operationId: readPdf
      parameters:
        - in: query
          name: file_id
          required: true
          schema:
            type: string
          description: The Google Drive file ID of the PDF to extract
      responses:
        '200':
          description: Successfully returned extracted PDF text
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: string
                    description: Extracted text from the PDF
        '401':
          description: Unauthorized - Invalid or missing token
        '500':
          description: Server error
      security:
        - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
